# Introducción a la Programación en JULIA 
## Notebook 4

Mauricio Tejada

ILADES - Universidad Alberto Hurtado

Mayo 2019

## Contenidos

- [Funciones](#4.-Funciones)
    - [Funciones Escalares](#4.1-Funciones-Escalares)
    - [Funciones Vectoriales](#4.2-Funciones-Vectoriales)
    - [Funciones Matriciales](#4.3-Funciones-Matriciales) 

## 4. Funciones

Julia y los paquetes que amplían sus capacidades proveen muchas funciones para realizar operaciones matemáticas y analizar datos. Para ordenar la discusión, categorizamos dichas funciones en matriciales, vectoriales y escalares. 

Aquí presentamos sólo algunos ejemplos de las funciones que les serán más útiles. 

### 4.1 Funciones Escalares

Las funciones escalares aplican operaciones sobre *escalares*. Son utilizables en escalares, vectores y matrices (y en general en cualquier Arreglo multidimensional). En el caso de los dos primeros, la operaciones se realizan elemento por elemento.

Algunos ejemplos:

- `sin`, `cos`: Seno, Coseno
- `exp`, `log`, `log10`, `abs`: Exponencial, logaritmo natural, logaritmo base 10 Valor absoluto
- `sign`: Signo (1 para positivo, -1 para negativo, 0 para cero) 
- `round`, `ceil`, `floor`: Redondea a entero

In [1]:
a = 2
expa = exp(a)

7.38905609893065

In [2]:
cosa = cos(a)

-0.4161468365471424

In [3]:
loga = log(a)

0.6931471805599453

In [4]:
b = -2.2
absa = abs(b)

2.2

Para aplicar funciones escalares a vectores y matrices usamos la construcción `funcion.()`, indicando así que la operación será realizada con cada elemento escalar que compone el vector o la matriz. Por ejemplo, usando un vector:

In [5]:
B = [2, 3]
expB = exp.(B)

2-element Array{Float64,1}:
  7.38905609893065
 20.085536923187668

Ahora usando una matriz:

In [6]:
C = rand(2,2)
logC = log.(C)

2×2 Array{Float64,2}:
 -0.245072  -0.111865
 -3.86277   -2.62166

Otras funciones escalares útiles son:

In [7]:
round(1.6)

2.0

In [8]:
ceil(1.2)

2.0

In [9]:
floor(1.2)

1.0

In [10]:
sign(-4)

-1

### 4.2 Funciones Vectoriales

Las funciones vectoriales aplican operaciones sobre *vectores*. Son utilizables en vectores y matrices. En el caso de las segundas, las operaciones se aplican por fila o por columna.

Algunos ejemplos:

- `maximum`, `minimum`, `findmax`, `findmin`: Máximo, mínimo.
- `length`: Tamaño de un vector
- `sort`, `sortrows`: Ordenar vector, ordenar filas de una matriz
- `sum`, `prod`, `cumsum`, `cumprod`: Suma, producto, suma acumulada, producto acumulado
- `mean`, `std`, `median`, `var`, `cov`: Media, desviación estándar, mediana, varianza, covarianza (para estas funciones se usa el paquete *Statistics* que viene en la instalación Base de Julia).

Ejemplo:

In [11]:
v = rand(6,1) # Generamos un vector

6×1 Array{Float64,2}:
 0.04122509765350335
 0.20862651529968157
 0.6426362054573778
 0.16583556523040333
 0.16327818248684878
 0.06372005885159893

In [12]:
vmax = maximum(v)

0.6426362054573778

In [13]:
vmin = minimum(v)

0.04122509765350335

In [14]:
length(v)

6

Las funciones vectoriales, según la operación que realicen tienen diversas opciones y posiblemente entregan más de un *resultado*. Ver opciones de cada función usando `?funcion`.

- Ejemplo de uso de funciones con más de un argumento de la función:

In [15]:
G = rand(5,3)

5×3 Array{Float64,2}:
 0.0887595  0.0855072  0.122308
 0.302627   0.310138   0.670346
 0.327429   0.541284   0.7231
 0.536855   0.843691   0.439307
 0.417173   0.133888   0.233029

In [16]:
a = maximum(G)

0.8436909313392533

Note que la función `maximum()` encuentra el máximo dentro de todos los elementos. Si nos interesa buscar el máximo por filas o por columnas utilizamos la opción `dims`:

In [17]:
a = maximum(G, dims=1) # Máximo por columnas

1×3 Array{Float64,2}:
 0.536855  0.843691  0.7231

In [18]:
a = maximum(G, dims=2) # Máximo por filas

5×1 Array{Float64,2}:
 0.1223075599477641
 0.6703458931676567
 0.7230997029731163
 0.8436909313392533
 0.4171731945197412

Esta misma lógica aplica a funciones como `sum()`, `prod()`, `cumsum()` y `cumprod()` (en el caso de los dos últimos la dimensión es un argumento obligatorio). Ejemplo:

In [19]:
G_suma_asum = cumsum(G, dims=1) # Acumula suma por columnas

5×3 Array{Float64,2}:
 0.0887595  0.0855072  0.122308
 0.391386   0.395645   0.792653
 0.718815   0.93693    1.51575
 1.25567    1.78062    1.95506
 1.67284    1.91451    2.18809

Las funciones `findmax` y `findmin` son ejemplos de funciones que tienen más de un resultado. En este caso, el valor del máximo (mínimo) y la posición del mismo. Ejemplo:

In [20]:
minval, posind = findmax(G)

(0.8436909313392533, CartesianIndex(4, 2))

Lo que indica que el máximo de $G$ es 0.96 y la posición dentro la matriz es fila 3 y columna 1. Para acceder a la fila y columna de `posind` usamos el índice ordinal: 

In [21]:
posind[1]

4

In [22]:
posind[2]

2

Cuando definimos la orientación fila o columna, `findmax` entregara el valor y la posición en cada fila o columna.

In [23]:
minval, posind = findmax(G,dims=1)

([0.5368546359828663 0.8436909313392533 0.7230997029731163], CartesianIndex{2}[CartesianIndex(4, 1) CartesianIndex(4, 2) CartesianIndex(3, 3)])

In [24]:
posind[1]

CartesianIndex(4, 1)

Note que usamos indexación para acceder a cada posición. Para para acceder al valor fila o columna de la fila o columna correspondiente usamos doble indexación:

In [25]:
posind[1][1] # Posición max en primera columna (fila,col). Además posición fila dentro esa columna.

4

Las funciones estadísticas como `mean`, `std`, `median`, `var` y `cov`, entre otras, son fundamentales en el análisis de datos. Para usarlas en Julia necesitamos primero cargar el paquete `Statistics` que viene en la instalación base de Julia.

In [26]:
using Statistics

In [27]:
mGc = mean(G)  # promedio de todos los elementos de la matriz.

0.38502934549780604

In [28]:
mGf = mean(G,dims=1) # promedios por columnas

1×3 Array{Float64,2}:
 0.334569  0.382902  0.437618

In [29]:
mGf = mean(G,dims=2)  # promedios por filas

5×1 Array{Float64,2}:
 0.09885808713436997
 0.4277035258534279
 0.530604434354558
 0.6066173862415334
 0.2613632939051412

In [30]:
mGc = std(G) # desvío estándar, todos los elementos

0.23992830544203808

In [31]:
mGf = mean(G,dims=1) # desvío estándar por columnas

1×3 Array{Float64,2}:
 0.334569  0.382902  0.437618

Para calcular covarianzas a partir de dos vectores usamos:

In [32]:
a = rand(5,1)
b = rand(5,1)
covab = cov(a,b)

1×1 Array{Float64,2}:
 -0.00036313531592260264

### 4.3 Funciones Matriciales

La funciones matriciales realizan operaciones sobre matrices y sólo son utilizables con este tipo de objetos.

Algunos ejemplos:

- `size`: Tamaño de la matriz.
- `inv`: Inversa (es mejor utilizar /).
- `eig`: Autovalores y autovectores.
- `cholesky`: Descomposición de Cholesky
- `det`: Determinante.
- `kron`: Producto de kronecker.
- `:` Convierte un matriz en un vector columna: vectorizar A[:].
- `reshape(A,filas,columnas)`: Cambio de dimensión.
- `diag`: Diagonal de una matriz (además matriz diagonal si el argumento es un vector).
- `triu`, `tril`: Matrices triangulares, superior e inferior.

Para contar con la funcionalidad del álgebra lineal debemos cargar el paquete `LinearAlgebra`:

In [33]:
using LinearAlgebra

Creamos una matriz $3 \times 3$ con números aleatorios para generar ejemplo sobre las funciones matriciales:

In [34]:
G = rand(3,3)

3×3 Array{Float64,2}:
 0.333335  0.257027  0.136347
 0.82768   0.867059  0.152616
 0.925303  0.991552  0.915607

El determinante de la matriz:

In [35]:
det_matriz = det(G)

0.0582087161793667

La inversa de la matriz:

In [36]:
inv(G)

3×3 Array{Float64,2}:
  11.0389    -1.72037  -1.35709
 -10.5931     3.07585   1.06478
   0.316022  -1.59238   1.31053

Los elementos de la diagonal principal son:

In [37]:
diag(G)

3-element Array{Float64,1}:
 0.333334806223623
 0.867058724963311
 0.9156069535883953

Para construir una matriz diagonal a partir de un vector usamos `diagm()` con la opción `0 =>` para indicar que el vector poblará la diagonal principal: 

In [38]:
diagm(0 => collect(1:4))

4×4 Array{Int64,2}:
 1  0  0  0
 0  2  0  0
 0  0  3  0
 0  0  0  4

Para vectorizar una matriz usamos `[:]` o `reshape(A,numfilas,1)` (el primer caso convierte la matriz en un Arreglo de una dimensión, mientras que el segundo convierte la matriz en un vector fila/columna dependiendo de las dimensiones):

In [39]:
vecG = G[:]

9-element Array{Float64,1}:
 0.333334806223623
 0.8276795809018942
 0.9253026743888646
 0.25702740383887424
 0.867058724963311
 0.991551564307277
 0.13634744795622789
 0.1526160780833028
 0.9156069535883953

In [40]:
vecG = reshape(G,9,1)

9×1 Array{Float64,2}:
 0.333334806223623
 0.8276795809018942
 0.9253026743888646
 0.25702740383887424
 0.867058724963311
 0.991551564307277
 0.13634744795622789
 0.1526160780833028
 0.9156069535883953

Calculamos los autovalores y autovectores de una matriz usando `eigen()`:

In [41]:
eigenval, eigenvecs = eigen(G)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
3-element Array{Float64,1}:
 0.07898079211537704
 0.47045517499126704
 1.5665645176686847
vectors:
3×3 Array{Float64,2}:
 -0.672685   0.0496444  -0.184691
  0.729946  -0.447249   -0.413095
 -0.121132   0.893031   -0.891763

In [42]:
eigenval

3-element Array{Float64,1}:
 0.07898079211537704
 0.47045517499126704
 1.5665645176686847

In [43]:
eigenvecs

3×3 Array{Float64,2}:
 -0.672685   0.0496444  -0.184691
  0.729946  -0.447249   -0.413095
 -0.121132   0.893031   -0.891763

Obtenemos matrices triangulares a partir de una matriz usando `triu()` (superior) y `tril()` (inferior):

In [44]:
F = ones(4,4)
tril(F)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0

In [45]:
triu(F)

4×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 0.0  1.0  1.0  1.0
 0.0  0.0  1.0  1.0
 0.0  0.0  0.0  1.0

Para crear una matriz de tamaño $4 \times 4$ y rellenarla del valor 5.0 usamos `fill()`:

In [46]:
H = fill(5.0, (4,4))

4×4 Array{Float64,2}:
 5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0

Finalmente, podemos transformar vectores en matrices usando `reshape()`:

In [47]:
v = collect(1:1:9)

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [48]:
R = reshape(v,3,3)

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9