# Introducción a la Programación en JULIA 
## Notebook 3

Mauricio Tejada

ILADES - Universidad Alberto Hurtado

## Contenidos

- [Matrices](#3.-Matrices)
    - [Secuencias](#3.1-Secuencias)
    - [Matrices Especiales](#3.2-Matrices-Especiales)
    - [Operaciones con Matrices](#3.3-Operaciones-con-Matrices)
    - [Referenciación y Submatrices](#3.4-Referenciación-y-Submatrices)
    - [Concatenar Matrices](#3.4-Referenciación-y-Submatrices)
    - [Arreglos de Mayor Dimensión](#3.6-Arreglos-de-Mayor-Dimensión)

## 3. Matrices

El álgebra lineal ocupa un lugar fundamental en el conjunto de herramientas que manejamos los economistas. En Julia, las matrices no son otra cosa que Arreglos (Arrays) homogéneos (que contienen sólo números) en dos dimensiones. Específicamente:

- Una matriz es un arreglo bidireccional que contiene números reales o complejos. Una matriz de dimensión $n \times m$ tiene $n$ filas y $m$ columnas. 
- Escalares representados por arreglos en una dimensión.
- Vectores fila y vectores columna están representados por arreglos en dos dimensiones con $1 \times m$ y $n \times 1$, respectivamente.

Existen dos formas de definir matrices: usando el teclado y/o leyendo archivos externos (de texto, Excel, etc). 

- *Usando el teclado:* Toda matriz se inicia y termina con `[ ]`, las columnas están separadas por espacios y filas por punto y coma. 
- *Leyendo archivos externos:* Se usan los comandos `dlmread`. Más adelante veremos detalles.

In [1]:
# Cargamos el paquete de herramientas de álgebra lineal de Julia (viene en la instalación base)
using LinearAlgebra

In [2]:
A = [1.0 2.0 3.0; 4.0 5.0 6.0; 7.0 8.0 9.0]

3×3 Array{Float64,2}:
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

In [3]:
B = [1.0 2.0 3.0; 4.0 5.0 6.0]

2×3 Array{Float64,2}:
 1.0  2.0  3.0
 4.0  5.0  6.0

In [4]:
C = [1.0; 2.0; 3.0]  # Note que este es un arreglo en una dimensión 

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [5]:
C = [1.0 2.0 3.0]' # Vector columna 3 x 1

3×1 Adjoint{Float64,Array{Float64,2}}:
 1.0
 2.0
 3.0

In [6]:
D = [1.0 4.0 3.0] # Vector fila 1 x 3

1×3 Array{Float64,2}:
 1.0  4.0  3.0

Para determinar el tamaño de una matriz utilizamos la función `size()`:

In [7]:
filas, cols = size(A)

(3, 3)

### 3.1 Secuencias

Es posible crear arreglos unidimensionales a partir de secuencias con valores equidistantes unos de otros.

- Forma 1: `inicio:incremento:fin` (incremento por defecto = 1). La secuencia termina en el número más cercano al número final definido. En Julia las secuencias son iterables son un tipo de objeto denominado iterable. Para convertir este objeto en un Arreglo se usa el comando `collect`.
- Forma 2: `range(inicio; tamaño, fin, incremento=1)` crea también in iterable con una secuencia de números. Si `tamaño` e `incremento` son provistos el último número es calculado automáticamente. Si `fin` e `incrementos` son provistos, el tamaño es calculado automáticamente. Finalmente, si `tamaño` y `fin` son provistos el incremento será calculado automáticamente. De nuevo, `collect` se usa par transformar este objeto iterable en un Arreglo.

Adicionalmente, existe la posibilidad de crear secuencias con número espaciados logarítmicamente.

Forma 3: `exp10.(range(inicio; tamaño, fin, incremento=1))` crea un vector de numero elementos en el intervalo [10^inicio,10^fin] espaciados logarítmicamente. Todas las opciones de `range()` aplican en este caso.

In [8]:
H0 = 1:10

1:10

In [9]:
H0 = collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [10]:
H1 = collect(1:0.6:3)

4-element Array{Float64,1}:
 1.0
 1.6
 2.2
 2.8

In [11]:
o = collect(10:-2:2)

5-element Array{Int64,1}:
 10
  8
  6
  4
  2

In [12]:
H2 = range(1,stop=4,step = 0.1)

1.0:0.1:4.0

In [13]:
H2 = collect(range(1,stop=8,length = 10))

10-element Array{Float64,1}:
 1.0
 1.7777777777777777
 2.5555555555555554
 3.3333333333333335
 4.111111111111111
 4.888888888888889
 5.666666666666667
 6.444444444444445
 7.222222222222222
 8.0

In [14]:
H3 = collect(exp10.(range(1,stop=3,length=3)))

3-element Array{Float64,1}:
   10.0
  100.0
 1000.0

### 3.2 Matrices Especiales

Julia tiene funciones especialmente diseñadas para construir cierto tipo de matrices:

- Matrices de ceros: `zeros(nfilas,ncolumnas)`
- Matrices de unos: `ones(nfilas,ncolumnas)`
- Matriz identidad: `eye(dimesion)`
- Matrices con números aleatorios: `rand(nfilas,ncolumnas)` (uniforme [0,1]) y `randn(nfilas,ncolumnas)` (Normal estándar).

In [15]:
ME1 = zeros(3,2)

3×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [16]:
ME2 = ones(4,1)

4×1 Array{Float64,2}:
 1.0
 1.0
 1.0
 1.0

In [17]:
ME3 = Matrix{Float64}(I, 2, 2)

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

Julia también tiene funcionalidad para crear matrices a partir de números aleatorios, esto usando las funciones `rand(nfilas,ncolumnas)` y `randn(nfilas,ncolumnas)` (el primero de una uniforme $[0,1]$ y el segundo de una Normal Estándar):

In [18]:
ME4 = rand(2,2)

2×2 Array{Float64,2}:
 0.476437  0.462704
 0.25391   0.507852

In [19]:
ME5 = randn(3,1)

3×1 Array{Float64,2}:
 -0.04482778954493163
  0.27467803596815427
 -1.7607505143037605

Notas: 
- Para generar número aleatorios de una distribución Normal con media $\mu$ y desviación estándar $\sigma$ usamos `mu+sig*randn(nfilas,ncols)`. 
- Para generar número aleatorios de una distribución Uniforme definida en el intervalo $[a,b]$ usamos `a+(b-a)*rand(nfilas,ncols)`.

Números aleatorios de una $N(2,0.5^2)$ se obtienen:

In [20]:
xn = 2.0*ones(3,3) + 0.5*randn(3,3)

3×3 Array{Float64,2}:
 1.26827  2.00713  2.24438
 2.47997  2.19968  3.37917
 1.81106  2.19398  2.46638

Números aleatorios de una $U(2,4)$ se obtienen:

In [21]:
xu = 2.0*ones(2,2) + (4-2)*rand(2,2)

2×2 Array{Float64,2}:
 2.93924  3.01067
 3.6774   3.43768

### 3.3 Operaciones con Matrices

El álgebra lineal define operaciones matriciales que Julia es capaz de realizar. Julia determina su uso is los arreglos califican como matrices (dos dimensiones). Todas las operaciones matriciales deben cumplir con los requerimiento de conformabilidad apropiados a la operación, caso contrario Julia indicara que existe un error.  *Note: Las operaciones con arreglos en una dimensión se realizan elemento por elemento.* 

- Suma `+` 
- Sustracción `-` 

In [22]:
A = [1 2 3; 4 5 6; 7 8 9];
B = [1 1 1; 2 2 2; 3 3 3];   

*Nota*: terminar una línea con `;` suprime la impresión del resultado en pantalla.

In [23]:
S = A + B

3×3 Array{Int64,2}:
  2   3   4
  6   7   8
 10  11  12

In [24]:
R = A - B

3×3 Array{Int64,2}:
 0  1  2
 2  3  4
 4  5  6

- Multiplicación `*`
- Potencia `^`

In [25]:
MM = A*B

3×3 Array{Int64,2}:
 14  14  14
 32  32  32
 50  50  50

In [26]:
P = A^2 # Idem P = A*A

3×3 Array{Int64,2}:
  30   36   42
  66   81   96
 102  126  150

- Traspuesta `'` o `transpose()`
- Inversa `inv(matriz)`
- División Izquierda '\' ($A^{-1}\times B$)
- División Derecha '/' ($B \times A^{-1}$)

In [27]:
C = rand(3,3)

3×3 Array{Float64,2}:
 0.420028  0.981017  0.0836713
 0.209223  0.620724  0.511472
 0.427229  0.496171  0.10856

In [28]:
Ctrans = transpose(C)

3×3 Transpose{Float64,Array{Float64,2}}:
 0.420028   0.209223  0.427229
 0.981017   0.620724  0.496171
 0.0836713  0.511472  0.10856

In [29]:
IV = inv(C)

3×3 Array{Float64,2}:
 -1.85848  -0.647941   4.48513
  1.95231   0.098226  -1.9675
 -1.6091    2.10098    0.553083

In [30]:
DI = C \ A    # Idem DI = inv(C)*A`

3×3 Array{Float64,2}:
  26.9457   28.9244   30.9031
 -11.4273  -11.3443  -11.2613
  10.6664   11.7114   12.7563

In [31]:
DI = inv(C)*A

3×3 Array{Float64,2}:
  26.9457   28.9244   30.9031
 -11.4273  -11.3443  -11.2613
  10.6664   11.7114   12.7563

- Operaciones elemento por elemento usan un punto precediendo al operador: `.*`, `.^`, `./`.

In [32]:
A = [1 2 3; 4 5 6; 7 8 9];
B = [1 1 1; 2 2 2; 3 3 3];  

In [33]:
Me = A.*B

3×3 Array{Int64,2}:
  1   2   3
  8  10  12
 21  24  27

In [34]:
Me = A./B

3×3 Array{Float64,2}:
 1.0      2.0      3.0
 2.0      2.5      3.0
 2.33333  2.66667  3.0

In [35]:
Pe = A.^2

3×3 Array{Int64,2}:
  1   4   9
 16  25  36
 49  64  81

### 3.4 Referenciación y Submatrices

Los elementos se una matriz se pueden referenciar de diversas formas:

- Usando `matriz[i,j]` donde `i` es la fila y `j` es la columna.

In [36]:
A

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [37]:
a22 = A[2,2]

5

In [38]:
a31 = A[3,1]

7

- Usando `matriz[ii:if,ci:cf]` para extraer más de un elemento. `ii` e `if` corresponden a la fila inicial y la fila final (lo mismo aplica a `ci` y `cf` para las columnas). Este método se usa para extraer submatrices o particionar.

In [39]:
subA1 = A[1:2,1:2]

2×2 Array{Int64,2}:
 1  2
 4  5

In [40]:
subA2 = A[2:3,1:3]

2×3 Array{Int64,2}:
 4  5  6
 7  8  9

Usar únicamente : indica toda la fila o columna según corresponda. El término `end` indica el último elemento.

In [41]:
subA3 = A[2,:]

3-element Array{Int64,1}:
 4
 5
 6

In [42]:
subA4 = A[:,2:3]

3×2 Array{Int64,2}:
 2  3
 5  6
 8  9

In [43]:
subA5 = A[2:end,3]

2-element Array{Int64,1}:
 6
 9

- Note que al usar matriz(ii:if,ji:jf) no estamos haciendo otra cosa que definir un vector secuencia (iterable) dentro la matriz. Por tanto es válido usar vectores para referenciar elementos (en secuencia o no).

In [44]:
B=rand(4,6);
Ind = 1:4;

In [45]:
subB1 = B[Ind,5]

4-element Array{Float64,1}:
 0.8750783583984212
 0.32461099178015207
 0.2465850516781527
 0.2374153793205398

In [46]:
subB2 = B[1:4,5]

4-element Array{Float64,1}:
 0.8750783583984212
 0.32461099178015207
 0.2465850516781527
 0.2374153793205398

- Podemos usar la misma lógica para elegir elementos que no son contiguos:

In [47]:
Indc = [1, 3, 4]

3-element Array{Int64,1}:
 1
 3
 4

In [48]:
Indf = [2, 4]

2-element Array{Int64,1}:
 2
 4

In [49]:
subB3 = B[Indf,Indc]

2×3 Array{Float64,2}:
 0.718146  0.373253  0.98508
 0.863863  0.444644  0.48635

### 3.5 Concatenar Matrices

Para concatenar matrices usamos los mismos procedimientos que para la definición de matrices usando el teclado, la única diferencia está en que los elementos son matrices. 

- La matriz se define en `[]`.
- Concatenar horizontalmente ` ` (espacio).
- Concatenar verticalmente `;`.

Nota: Ser cuidadoso con la conformabilidad de las matrices.

In [50]:
A = rand(3,2);
B = rand(2,2);

Concatenar verticalmente A y B:

In [51]:
C = [A ; B]

5×2 Array{Float64,2}:
 0.648599  0.89093
 0.422508  0.701603
 0.28877   0.467927
 0.284474  0.402947
 0.410712  0.0403167

Concatenar horizontalmente la traspuesta de A con B:

In [52]:
D = [A' B]

2×5 Array{Float64,2}:
 0.648599  0.422508  0.28877   0.284474  0.402947
 0.89093   0.701603  0.467927  0.410712  0.0403167

### 3.6 Arreglos de Mayor Dimensión

Julia es capaz de manipular matrices de mayor dimensión (ejemplo 3D). Todas las reglas de creación, referenciación, partición y concatenación aplican.

*Nota: Sólo operaciones elemento por elemento son utilizables con arreglos de mayor dimensión.*

In [53]:
A = rand(2,2,2)

2×2×2 Array{Float64,3}:
[:, :, 1] =
 0.426227  0.488331
 0.763232  0.208264

[:, :, 2] =
 0.553193  0.0315616
 0.821481  0.467431

La referenciación a los elementos funciona de la misma forma. Por ejemplo, encontramos el elemento de la fila 2, columna 2, grupo (matriz) 1:

In [54]:
A[2,2,1]

0.20826446817410416